#!/bin/sh

VERBOSE_INSTALL=yes

set -e

if [ -f /etc/debian_version ] ; then
	/usr/share/dtc/admin/install/uninstall
	. /usr/share/dtc/admin/install/debian_config
	. ${DTC_SAVED_INSTALL_CONFIG}
	if [ ""$conf_apache_version = "2" ] ; then
		PATH_HTTPD_CONF=/etc/apache2/apache2.conf
	else
		PATH_HTTPD_CONF=/etc/apache/httpd.conf
	fi
	. /usr/share/dtc/admin/install/functions
fi

if [ "`uname -s`" -eq "FreeBSD" ]; then
	echo "FreeBSD detected"
	. /usr/local/www/dtc/admin/install/functions
fi

DTCsetupDaemons
