#!/bin/sh

VERBOSE_INSTALL=yes

if [ -f /etc/debian_version ] ; then
	. /usr/share/dtc/admin/install/debian_config
	. /usr/share/dtc/admin/install/functions

	PATH_HTTPD_CONF=/etc/apache2/apache2.conf
	DTCuninstallDaemons
	PATH_HTTPD_CONF=/etc/apache/httpd.conf
	uninstallHttpdConfig
fi
