#!/bin/sh

set -e

. /usr/share/dtc/admin/install/debian_config
. /usr/share/dtc/admin/install/functions

createDTCuserAndGroup
mkdir -p /var/lib/dtc/dtc-xenservers-rrds
chown -R dtc:dtcgrp /var/lib/dtc/dtc-xenservers-rrds

# Set the logfile with correct rights
touch /var/log/dtc-stats-daemon.log
chown dtc:dtcgrp /var/log/dtc-stats-daemon.log

# Automatically added by dh_installinit/13.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/dtc-stats-daemon" ]; then
		update-rc.d dtc-stats-daemon defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d dtc-stats-daemon $_dh_action || exit 1
	fi
fi
# End automatically added section


exit 0
