#!/bin/sh
#
# Welcome to the DTC install maker !
# This will produce the tarball package
# Maintainer: Thomas GOIRAND <thomas [ at ] goirand.fr>
# please do not ship with you packages
# this is only a small coder tool...
#

set -e

VERS=`cat bin/version`
RELS=`cat bin/release`
VERSION=$VERS"."$RELS
UNIX_TYPE=bsd
PKG_BUILD="dtc-"$VERSION
PORT_BUILD=bsd/tmp/sysutils/dtc
ARCH_NAME=$PKG_BUILD".tar.gz"
BSD_SOURCE_DIR="bsd"
if [ -z "${DESTDIR}" ] ; then
	DEST_DIR=".."
fi
if [ -z "${BUILD_DIR}" ] ; then
	BUILD_DIR="bsd/tmp"
fi

CURDIR=`pwd`
SRC_COPY_DIR=${CURDIR}/${BUILD_DIR}/${PKG_BUILD}
mkdir -p ${BUILD_DIR}

# Specific BSD package actions :
# Create an empty Makefile in the "sources" of DTC so nothing is to be built
echo "--- Making source snapshot $ARCH_NAME ---"
echo "-> Copying source package files with make source-copy DESTFOLDER=${SRC_COPY_DIR}"
make source-copy DESTFOLDER=${SRC_COPY_DIR}
cd $CURDIR/${BUILD_DIR}
echo "-> Creating tarball archive"
tar -czf ${ARCH_NAME} ${PKG_BUILD}
cd $CURDIR
if [ ! "$DEST_DIR" = "." -a ! "$DEST_DIR" = "./" -a ! "$DEST_DIR" = "$CURDIR" ] ; then
	mv ${BUILD_DIR}/$ARCH_NAME $DEST_DIR/
fi
echo " --- Succesfully made BSD source snapshot ${DEST_DIR}/${ARCH_NAME} ---"

echo " --- Making BSD port tree for version "$VERSION" ---"
# Move bsd version as if it was in ${PREFIX} so we can do lookups in it
echo "===> Creating port files in $PORT_BUILD"
mkdir -p $PORT_BUILD/files						# Make  dtc port dir and copy static files in it
sed "s/__VERSION__/${VERSION}/" $BSD_SOURCE_DIR/dtc/Makefile >$PORT_BUILD/Makefile	# Create Makefile with correct port version
cp $BSD_SOURCE_DIR/dtc/install.sh $PORT_BUILD/files/dtc-install.in		# Create package install script
chmod 644 $PORT_BUILD/files/dtc-install.in
cp $BSD_SOURCE_DIR/dtc/uninstall.sh $PORT_BUILD/files/dtc-deinstall.in		# Create package uninstall script
chmod 644 $PORT_BUILD/files/dtc-deinstall.in
cp $BSD_SOURCE_DIR/dtc/pkg-message $PORT_BUILD
cp $BSD_SOURCE_DIR/dtc/pkg-descr $PORT_BUILD

echo "===> Calculating source package MD5 sum and size"
# Make the md5 sum file in this distinfo
SIZE=`ls -ALln ${DEST_DIR}/${ARCH_NAME} | awk '{print $5}'`
# If /sbin/md5, assume it's the BSD md5 binary, otherwise use the one in /usr/bin/md5sum
if [ -e /sbin/md5 ] ; then
	BSDSUM=`md5 ${DEST_DIR}/${ARCH_NAME}`
else
	BSDSUM=`md5sum ${DEST_DIR}/${ARCH_NAME} | cut -f1 -d" "`
fi
echo "MD5 (${ARCH_NAME}) = ${BSDSUM}
SIZE (${ARCH_NAME}) = ${SIZE}" >$PORT_BUILD/distinfo

echo "===> Creating package list file"
cd $CURDIR
PKG_PLIST_BUILD=$CURDIR/${BUILD_DIR}/PKG_PLIST_BUILD
mkdir -p $PKG_PLIST_BUILD
echo "-> Calling make install-dtc-common to calculate list in $PKG_PLIST_BUILD"
make install-dtc-common DESTDIR=$PKG_PLIST_BUILD DTC_APP_DIR=/usr/local/www DTC_GEN_DIR=/usr/local/var CONFIG_DIR=/usr/local/etc \
	DTC_DOC_DIR=/usr/local/share/doc MANUAL_DIR=/usr/local/man BIN_DIR=/usr/local/bin UNIX_TYPE=bsd 2>&1 >/dev/null
echo "-> Building list of files"
cd $PKG_PLIST_BUILD
find . -type f | sed "s/\.\/usr\/local/%%LOCALBASE%%/" >$CURDIR/$PORT_BUILD/pkg-plist.tmp
echo "%%LOCALBASE%%/www/dtc/admin/gfx
%%LOCALBASE%%/www/dtc/admin/imgcache
%%LOCALBASE%%/www/dtc/shared/mysql_config.php
%%LOCALBASE%%/www/dtc/client/gfx
%%LOCALBASE%%/www/dtc/client/imgcache
sbin/dtc-install
sbin/dtc-deinstall
%%LOCALBASE%%/dtc/email/gfx
%%LOCALBASE%%/dtc/email/imgcache" >>$CURDIR/$PORT_BUILD/pkg-plist.tmp
find usr/local -type d -printf "@dirrm %h/%f\n" | grep -v "/etc" | sed "s/usr\/local/%%LOCALBASE%%/" | sort -r >>$CURDIR/$PORT_BUILD/pkg-plist.tmp
NBR_LINE=`cat $CURDIR/$PORT_BUILD/pkg-plist.tmp | wc -l`
cat $CURDIR/$PORT_BUILD/pkg-plist.tmp | head -n $(( $NBR_LINE - 2 )) >$CURDIR/$PORT_BUILD/pkg-plist.tmp2
cat $CURDIR/$PORT_BUILD/pkg-plist.tmp2 | grep -v "mysql_config.php" >$CURDIR/$PORT_BUILD/pkg-plist
echo "@dirrm %%DTCROOT%%/etc/zones
@dirrm %%DTCROOT%%/etc
@dirrm %%DTCROOT%%" >>$CURDIR/$PORT_BUILD/pkg-plist
echo "-> Deleting temp files"
rm $CURDIR/$PORT_BUILD/pkg-plist.tmp $CURDIR/$PORT_BUILD/pkg-plist.tmp2
rm -r $PKG_PLIST_BUILD
cd $CURDIR

echo "-> Adding slave ports to the archive"
mkdir -p ${BUILD_DIR}/sysutils/dtc-postfix-courier
cp $BSD_SOURCE_DIR/dtc-postfix-courier/Makefile ${BUILD_DIR}/sysutils/dtc-postfix-courier
cp $BSD_SOURCE_DIR/dtc-postfix-courier/pkg-descr ${BUILD_DIR}/sysutils/dtc-postfix-courier
mkdir -p ${BUILD_DIR}/sysutils/dtc-toaster
cp $BSD_SOURCE_DIR/dtc-toaster/Makefile ${BUILD_DIR}/sysutils/dtc-toaster
cp $BSD_SOURCE_DIR/dtc-toaster/pkg-descr ${BUILD_DIR}/sysutils/dtc-toaster

echo "===> Creating .uue archive file"
# Make the file archive
cd ${BUILD_DIR}
tar -czf "dtcBSDport-"$VERSION".tar.gz" sysutils
cd $CURDIR

mv ${BUILD_DIR}/dtcBSDport-"$VERSION".tar.gz $DEST_DIR

echo "===> Deleting temp files"
rm -r ${BUILD_DIR}
