.TH dtc_autodeploy 8
.SH NAME
dtc_autodeploy \- Autodeploy the DTC panel
.SH SYNOPSIS
.B dtc_autodeploy
.I PASSWORD

.SH DESCRIPTION
.B dtc_autodeploy
This shell script will automatically install
the DTC control panel with one unique command.
It's used to deploy automatically the control
panel after installing a server.

.SH "VERSION"
See
.B http://www.gplhost.com/software-dtc.html
for updates.
