# New ports collection makefile for:    dtc-toaster
# Date created:                         20 November 2006
# Whom:                                 Marc G. Fournier <scrappy@freebsd.org>
#
# $FreeBSD: ports/sysutils/dtc-toaster/Makefile,v 1.6 2007/09/29 12:22:20 pav Exp $
#

PORTREVISION=   4
PKGNAMESUFFIX=  -toaster

MAINTAINER=     scrappy@freebsd.org

CONFLICTS=      dtc-[0-9]*

WITH_WEBALIZER=yes
WITH_VISITORS=yes
WITH_AWSTATS=yes
WITH_MHONARC=yes
WITH_MLMMJ=yes
WITH_PUREFTPD=yes
WITH_POSTFIX=yes
WITH_APACHE2=yes
WITH_PHP5=yes

DESCR=          ${.CURDIR}/pkg-descr

MASTERDIR=      ${.CURDIR}/../dtc

.include "${MASTERDIR}/Makefile"
