CREATE TABLE IF NOT EXISTS `ip_port_service` (
	`id` INT NOT NULL AUTO_INCREMENT ,
	`ip` VARCHAR( 16 ) NOT NULL ,
	`port` VARCHAR( 16 ) NOT NULL ,
	`service` VARCHAR( 64 ) NOT NULL ,
	PRIMARY KEY ( `id` )
) TYPE = MYISAM ;
