CREATE TABLE IF NOT EXISTS new_admin (
  id int(9) NOT NULL auto_increment,
  reqadm_login varchar(64) NOT NULL default '',
  reqadm_pass varchar(16) NOT NULL default '',
  domain_name varchar(64) NOT NULL default '',
  family_name varchar(64) NOT NULL default '',
  first_name varchar(64) NOT NULL default '',
  comp_name varchar(64) NOT NULL default '',
  iscomp enum('yes','no') NOT NULL default 'yes',
  vat_num varchar(128) NOT NULL default '',
  email varchar(255) NOT NULL default '',
  phone varchar(20) NOT NULL default '',
  fax varchar(20) NOT NULL default '',
  addr1 varchar(100) NOT NULL default '',
  addr2 varchar(100) NOT NULL default '',
  addr3 varchar(100) NOT NULL default '',
  zipcode varchar(32) NOT NULL default '',
  city varchar(64) NOT NULL default '',
  state varchar(32) NOT NULL default '',
  country char(2) NOT NULL default '',
  paiement_id int(9) NOT NULL default '0',
  product_id int(9) NOT NULL default '0',
  custom_notes text NOT NULL,
  vps_location varchar(255) NOT NULL default '',
  vps_os varchar(255) NOT NULL default '',
  shopper_ip varchar(16) NOT NULL default '',
  `date` date NOT NULL default '0000-00-00',
  `time` time NOT NULL default '00:00:00',
  last_used_lang varchar(32) NOT NULL default 'en_US.UTF-8',
  add_service enum('yes','no') NOT NULL default 'no',
  PRIMARY KEY  (id)
) TYPE=MyISAM;
