CREATE TABLE IF NOT EXISTS ssh_access (
  login varchar(50) NOT NULL default '',
  uid int(5) NOT NULL default '65534',
  gid int(5) NOT NULL default '65534',
  crypt varchar(50) NOT NULL default '',
  password varchar(50) NOT NULL default 'passwd',
  homedir varchar(255) NOT NULL default '',
  count int(11) default '0',
  fhost varchar(50) default NULL,
  faddr varchar(15) default NULL,
  ftime timestamp(14) NOT NULL,
  fcdir varchar(150) default NULL,
  fstor int(11) default '0',
  fretr int(11) default '0',
  bstor int(11) default '0',
  bretr int(11) default '0',
  creation datetime default NULL,
  ts timestamp(14) NOT NULL,
  frate int(11) default '5',
  fcred int(2) default '15',
  brate int(11) default '5',
  bcred int(2) default '1',
  flogs int(11) default '0',
  size int(11) NOT NULL default '0',
  shell varchar(64) NOT NULL default '/bin/dtc-chroot-shell',
  hostname varchar(64) NOT NULL default 'anotherlight.com',
  login_count int(11) NOT NULL default '0',
  last_login datetime NOT NULL default '0000-00-00 00:00:00',
  dl_bytes int(14) NOT NULL default '0',
  ul_bytes int(14) NOT NULL default '0',
  dl_count int(14) NOT NULL default '0',
  ul_count int(14) NOT NULL default '0',
  UNIQUE KEY login (login),
  KEY hostname (hostname)
) TYPE=MyISAM;
