CREATE TABLE IF NOT EXISTS vps(
  id int(11) NOT NULL auto_increment,
  owner varchar(64) NOT NULL default '',
  vps_server_hostname varchar(255) NOT NULL default '',
  vps_xen_name varchar(64) NOT NULL default '',
  start_date date NOT NULL default '0000-00-00',
  expire_date date NOT NULL default '0000-00-00',
  hddsize int(9) NOT NULL default '1',
  ramsize int(9) NOT NULL default '48',
  bandwidth_per_month_gb int(9) NOT NULL default '1',
  product_id int(9) NOT NULL default '0',
  operatingsystem varchar(64) NOT NULL default 'debian',
  vncpassword varchar(64) NOT NULL default 'none',
  howtoboot varchar(256) NOT NULL default 'hdd',
  installed enum('yes','no') NOT NULL default 'no',
  bsdkernel enum('normal','install') NOT NULL default 'normal',
  monitoring_email varchar(255) NOT NULL default '',
  monitor_ping enum('yes','no') NOT NULL default 'no',
  monitor_ssh enum('yes','no') NOT NULL default 'no',
  monitor_http enum('yes','no') NOT NULL default 'no',
  monitor_smtp enum('yes','no') NOT NULL default 'no',
  monitor_pop3 enum('yes','no') NOT NULL default 'no',
  monitor_imap4 enum('yes','no') NOT NULL default 'no',
  monitor_ftp enum('yes','no') NOT NULL default 'no',
  PRIMARY KEY  (id),
  UNIQUE KEY vps_server_hostname (vps_server_hostname,vps_xen_name),
  KEY ownerindex (owner)
)TYPE=MyISAM
