#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/dtc-dos-firewall" ]; then
		update-rc.d dtc-dos-firewall defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d dtc-dos-firewall $_dh_action || exit 1
	fi
fi
# End automatically added section
