#!/bin/sh
set -e
# Automatically added by dh_installinit/13.2.1
if [ -x "/etc/init.d/dtc-dos-firewall" ] && [ "$1" = remove ]; then
	invoke-rc.d dtc-dos-firewall stop || exit 1
fi
# End automatically added section
