#!/bin/bash
#
#       /etc/rc.d/init.d/dtc-stats-daemon
#
# Starts the dtc-stats-daemon daemon
#
# chkconfig: 345 95 5
# description: dtc-xen VM statistics for the dtc web control panel
# processname: /usr/share/dtc/admin/dtc-stats-daemon

MY_DAEMON=/usr/share/dtc/admin/dtc-stats-daemon.php

test -x ${MY_DAEMON} || exit 0

. /etc/rc.d/init.d/functions
. /lib/lsb/init-functions

RETVAL=0

case "$1" in
start)
#	start_daemon "Starting dtc-xen statistic daemon" "dtc-stats-daemon"
	daemon ${MY_DAEMON}
	RETVAL=$?
#	log_end_msg ${RETVAL}
	exit $RETVAL
;;
stop)
#	log_daemon_msg "Stoping dtc-xen statistic daemon" "dtc-stats-daemon"
	killproc ${MY_DAEMON}
#	log_end_msg $?
;;
status)
	status ${MY_DAEMON}
;;
restart|reload|force-reload)
	$0 stop
	sleep 1
	$0 start
;;
*)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
