DD_roundies.addRule('.contentslide, .contentlogpanel', '0 20px 0 20px');
DD_roundies.addRule('.panelside, .trigger, a.trigger, a.trigger:hover', '0 20px 20px 0');
DD_roundies.addRule('.highlight, #iconbar li, .box_wnb_content_nb_item, .box_wnb_content_nb_item_select', '20px');
DD_roundies.addRule('.input_btn_container, .input_btn_container-hover, .box_wnb_nb_input_btn_container, .box_wnb_nb_input_btn_container-hover', '10px');
DD_roundies.addRule('.console_output, .rad-border', '9px', true);
DD_roundies.addRule('#tooltip.default', '8px', true);
DD_roundies.addRule('.box_wnb_nb_items li, .box_wnb_nb_item-hover, .box_wnb_nb_item_select', '5px');
DD_roundies.addRule('.box_wnb_tv_leaf, .box_wnb_tv_leaf-hover, .box_wnb_tv_leaf_select, .box_wnb_tv_leaf_open, .box_wnb_tv_leaf_leaf, .box_wnb_tv_leaf_leaf-hover, .box_wnb_tv_leaf_leaf_select, .alternatecolorline', '5px');
DD_roundies.addRule('input,select,textarea', '3px');
﻿document.write('<style>');
document.write('.panelside {-ms-filter: "alpha(opacity=85)"; filter: alpha(opacity=85); opacity: .85; zoom:1;}');
document.write('.highlight {-ms-filter: "alpha(opacity=90)"; filter:alpha(opacity=90); zoom:1;}');
document.write('toppanel {-ms-filter: "alpha(opacity=80)"; filter:alpha(opacity=80); zoom:1;}');
document.write('<\/style>');
