DD_roundies.addRule('.contentslide, .contentlogpanel', '0 20px 0 20px', true);
DD_roundies.addRule('.panelside, .trigger, a.trigger, a.trigger:hover', '0 20px 20px 0', true);
DD_roundies.addRule('.highlight, #iconbar li, .box_wnb_content_nb_item, .box_wnb_content_nb_item_select', '20px', true);
DD_roundies.addRule('.input_btn_container, .input_btn_container-hover, .box_wnb_nb_input_btn_container, .box_wnb_nb_input_btn_container-hover', '10px', true);
DD_roundies.addRule('.console_output, .rad-border', '9px', true);
DD_roundies.addRule('#tooltip.default', '8px', true);
DD_roundies.addRule('.box_wnb_nb_items li, .box_wnb_nb_item-hover, .box_wnb_nb_item_select, .box_wnb_tv_leaf, .box_wnb_tv_leaf-hover, .box_wnb_tv_leaf_select, .box_wnb_tv_leaf_open, .box_wnb_tv_leaf_leaf, .box_wnb_tv_leaf_leaf-hover, .box_wnb_tv_leaf_leaf_select, .alternatecolorline', '5px', true);
DD_roundies.addRule('input,select,textarea', '3px', true);
﻿document.write('<style>');
document.write('.panelside {filter: alpha(opacity=85); opacity: .85;}');
document.write('.highlight {-moz-opacity : 0.9; filter:alpha(opacity=90);}');
document.write('toppanel {-moz-opacity : 0.8; filter:alpha(opacity=80);}');
document.write('<\/style>');
