.TH dtc-chroot-shell 8
.SH NAME
dtc-chroot-shell \- Make it possible for dtc shared hosting users to log into a chrooted shell
.SH SYNOPSIS
.B dtc

.SH DESCRIPTION
.B dtc-chroot-shell
This shell script is a part of the dtc web hosting
control panel package.

This script will be used each time a user will connect to his hosting
account with ssh. This is not to be used by you as a tool on the shell.
Look in it, it's VERY short.

.SH "VERSION"
This documentation describes
.B dtc-chroot-shell
See
.B http://www.gplhost.com/software-dtc.html
for updates.
