#!/bin/sh

set -e

DTC_PATH=/usr/share/dtc

usages () {
	echo "dtc_migrate <DESTINATION_SERVER>"
	exit 1
}
if [ $# -lt 1 ]; then
	usages
fi
if [ $# -gt 1 ]; then
	usages
fi
DST=${1}

echo "===> DTC Migrate script: upload of all DBs"
echo -n "Getting local IP: "
my_ip=`${DTC_PATH}/admin/guess_ip.sh`
echo ${my_ip}

scp ${DTC_PATH}/admin/guess_ip.sh ${DST}:${DTC_PATH}/admin/
echo -n "Getting remote IP: "
rem_ip=`ssh ${DST} ${DTC_PATH}/admin/guess_ip.sh`
echo ${rem_ip}

if [ -f /etc/redhat-release ] ; then
	MKTEMP="mktemp -p /tmp"
else
	MKTEMP="mktemp -t"
fi

bk_dir=`${MKTEMP} -d DTC_migrate.XXXXXX`
echo "Will backup in ${bk_dir}"

echo -n "Will import in "
rem_dir=`ssh ${DST} "${MKTEMP} -d DTC_migrate.XXXXXX"`
echo ${rem_dir}

php migrate_to_server.php ${bk_dir} ${my_ip} ${rem_ip}
sed -i 's/$my_ip/$rem_ip/' $bk_dir/dtc.sql

echo "Copying SQL files to remote:"
scp $bk_dir/*.sql ${DTC_PATH}/admin/dtc_import_all_dbs $DST:$rem_dir

echo "Starting the dtc_import_all_dbs script on remote:"
ssh $DST $rem_dir/dtc_import_all_dbs $rem_dir

echo "===> DTC Migrate script: upload of all files"
echo "rsync -e ssh -azvp /var/www/sites/ ${DST}:/var/www/sites"
nice rsync -e ssh -azvp /var/www/sites/ ${DST}:/var/www/sites
echo "rsync of the MLMMJ and /etc/dtc folders"
nice rsync -e ssh -azvp /etc/mlmmj/ ${DST}:/etc/mlmmj
nice rsync -e ssh -azvp /etc/dtc/ ${DST}:/etc/dtc
