#!/bin/sh

set -e

usages () {
	echo "Usages: dtcpassadm -{l,p,a} [param]"
	echo "With -l = list users and pass"
	echo "     -p user pass = set pass as password for user"
	echo "     -a user pass = adds user with password pass"
	echo "     -d user = removes user"
	exit 1
}

if [ $# -lt 1 ] ; then
	usages
fi

case ${1} in
"-l")
	if [ $# != 1 ] ; then usages ; fi
	# Show passwords:
	mysql --defaults-file=/etc/mysql/debian.cnf -Ddtc --execute="SELECT pseudo,tikadm_pass FROM tik_admins"
;;
"-p")
	if [ $# != 3 ] ; then usages ; fi
	# Change a password
	mysql --defaults-file=/etc/mysql/debian.cnf -Ddtc --execute="UPDATE tik_admins SET tikadm_pass='${3}' WHERE pseudo='${2}'"
;;
"-a")
	if [ $# != 3 ] ; then usages ; fi
	# Adds a user
	mysql --defaults-file=/etc/mysql/debian.cnf -Ddtc --execute="INSERT INTO tik_admins (pseudo,tikadm_pass) VALUES ('${2}','${3}')"
;;
"-d")
	if [ $# != 2 ] ; then usages ; fi
	# Delete a user
	mysql --defaults-file=/etc/mysql/debian.cnf -Ddtc --execute="DELETE FROM tik_admins WHERE pseudo='${2}'"
;;
esac
exit 0
