#!/bin/sh

UNIX_TYPE=slackware
VERBOSE_INSTALL=yes

CONF_DTC_SYSTEM_USERNAME=dtc
CONF_DTC_SYSTEM_GROUPNAME=dtcgrp

conf_apache_version=2
PATH_HTTPD_CONF="/etc/httpd/httpd.conf"
PATH_APACHE_PID_FILE="/var/run/httpd/httpd.pid"

PATH_PHP_CGI="/usr/bin/php-cgi"
PATH_PHP_INI="/etc/httpd/php.ini"
PATH_NAMED_CONF="/etc/named.conf"
PATH_PROFTPD_CONF="/etc/proftpd.conf"
PATH_DOVECOT_CONF="/etc/dovecot.conf"
PATH_COURIER_CONF_PATH="/etc/courier"
PATH_COURIER_AUTHD_CONF_PATH="/etc/authlib"
PATH_USERDB_BIN="/usr/sbin/userdb"
PATH_POSTFIX_CONF="/etc/postfix/main.cf"
PATH_POSTFIX_ETC="/etc/postfix"
PATH_SASL_PASSWD2="/usr/sbin/saslpasswd2"
PATH_MAILDROP_BIN="/usr/bin/maildrop"
PATH_QMAIL_CTRL="/var/qmail/control"
PATH_QMAIL_NEWU="/var/qmail/bin/qmail-newu"
PATH_CYRUS_CONF="/usr/local/etc/imapd.conf"

FREERADIUS_ETC="/etc/raddb"
PATH_CRONTAB_CONF="/var/spool/cron/crontabs/root"
PATH_AWSTATS_ETC="/etc/awstats"
PATH_AMAVISD_CONF="/etc/amavisd.conf"
PATH_CLAMAV_CONF="/etc/clamd.conf"

PATH_CGIBIN="/var/www/cgi-bin"
PATH_SASLLIB="/usr/lib/sasl2"
PATH_SUDOERS_CONF="/etc/sudoers"
PATH_RRDTOOL="/usr/bin/rrdtool"
PATH_DTC_SHARED="/usr/share/dtc"
PATH_DTC_ETC=$PATH_DTC_SHARED"/etc"
PATH_DTC_ADMIN=$PATH_DTC_SHARED"/admin"
PATH_DTC_CLIENT=$PATH_DTC_SHARED"/client"

USER_ADD_CMD=useradd
GROUP_ADD_CMD=groupadd
USER_MOD_CMD=usermod
PASSWD_CMD=passwd

MYSQL_DB_SOCKET_PATH="/var/run/mysql/mysql.sock"
MYSQL_SERVER="myadm.formosahost.com"
MYSQL_CLIENT='spider%.formosahost.com'
MX_MAIL="postman"
SQ_DATA="/var/lib/squirrelmail/data"
SQ_ATTACH="/var/lib/squirrelmail/attach"
DKFILTER_INIT_SCRIPT=/etc/init.d/dkfilter
