<?php

global $txt_lists_main_title_rights;
global $txt_lists_main_title_header;
global $txt_lists_main_title_archive;
global $txt_lists_main_title_digest;
global $txt_lists_main_title_notification;
global $txt_lists_main_title_smtp_config;

$txt_lists_main_title_rights = array (
  "fr" => "Droits",
  "en" => "Rights",
  "hu" => "",
  "it" => "Permessi",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_main_title_header = array (
  "fr" => "Entête",
  "en" => "Header",
  "hu" => "",
  "it" => "Header",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_main_title_archive = array (
  "fr" => "Archive",
  "en" => "Archive",
  "hu" => "",
  "it" => "Archivio",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_main_title_digest = array (
  "fr" => "Digest",
  "en" => "Digest",
  "hu" => "",
  "it" => "Digest",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_main_title_notification = array (
  "fr" => "Alertes",
  "en" => "Notifications",
  "hu" => "",
  "it" => "Notifiche",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_main_title_smtp_config = array (
  "fr" => "Configuration SMTP",
  "en" => "SMTP configuration",
  "hu" => "",
  "it" => "Configurazione SMTP",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_list_name = array (
  "fr" => "Nom de la liste :",
  "en" => "Name of the list:",
  "hu" => "",
  "it" => "Nome della lista:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_list_name = array (
  "fr" => "Propriétaire :",
  "en" => "Owner:",
  "hu" => "",
  "it" => "Proprietario:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_closedlist = array (
  "fr" => "Liste fermée :",
  "en" => "Closed list:",
  "hu" => "",
  "it" => "Lista chiusa:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_moderated = array (
  "fr" => "Modérée :",
  "en" => "Moderated:",
  "hu" => "",
  "it" => "Moderata:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_moderators = array (
  "fr" => "Modérateurs :",
  "en" => "Moderators:",
  "hu" => "",
  "it" => "Moderatori:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_subonlypost = array (
  "fr" => "Post inscrits uniquement :",
  "en" => "Subscribers only post:",
  "hu" => "",
  "it" => "Post solo agli iscritti:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_notifysub = array (
  "fr" => "Avertir des inscriptions :",
  "en" => "Notify new subscribtions:",
  "hu" => "",
  "it" => "Notifica nuove iscrizioni:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_noarchive = array (
  "fr" => "Pas d'archives :",
  "en" => "No archives:",
  "hu" => "",
  "it" => "Nessun archivio:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_nosubconfirm = array (
  "fr" => "Pas de confirmation d'inscription :",
  "en" => "No subscribtion confirmation:",
  "hu" => "",
  "it" => "Nessuna conferma iscrizione:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_noget = array (
  "fr" => "Pas de fonction get-N :",
  "en" => "No get-N function:",
  "hu" => "",
  "it" => "Disabilita funzione get-N:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_subonlyget = array (
  "fr" => "Fonction get-N uniquement pour les inscrits :",
  "en" => "get-N function only for subscribers:",
  "hu" => "",
  "it" => "Funzione get-N solo iscritti:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_tocc = array (
  "fr" => "To: ou Cc: non obligatoire :",
  "en" => "To: or Cc: not mandatory:",
  "hu" => "",
  "it" => "To: o Cc: non obbligatori:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_addtohdr = array (
  "fr" => "Ajouter entête To: :",
  "en" => "Add To: header:",
  "hu" => "",
  "it" => "Aggiungi all'header To:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_notoccdenymails = array (
  "fr" => "Rejetter si sans To: ou Cc: :",
  "en" => "Deny if no To: or Cc::",
  "hu" => "",
  "it" => "Respingi se senza To: o Cc:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_noaccessdenymails = array (
  "fr" => "Alerte lorsque post et pas d'acces :",
  "en" => "Notify when post and no access:",
  "hu" => "",
  "it" => "Notifica quando invia e nessun accesso:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_nosubonlydenymails = array (
  "fr" => "Alerte lorsque post et pas inscrit :",
  "en" => "Notify when post and not subscribed:",
  "hu" => "",
  "it" => "Notifica quando invia e non iscritto:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_prefix = array (
  "fr" => "Préfix du sujet :",
  "en" => "Subject prefix:",
  "hu" => "",
  "it" => "Prefisso del subject:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_memorymailsize = array (
  "fr" => "Taille memoire max des messages :",
  "en" => "Max mail memory size:",
  "hu" => "",
  "it" => "Massima memoria dei messaggi:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_relayhost = array (
  "fr" => "Serveur SMTP relai :",
  "en" => "SMTP relay server:",
  "hu" => "",
  "it" => "Server relay SMTP:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_digestinterval = array (
  "fr" => "Intervale du digest :",
  "en" => "Digest interval:",
  "hu" => "",
  "it" => "Intervallo di digest:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_digestmaxmails = array (
  "fr" => "Nombre de message max du digest :",
  "en" => "Digest max mails:",
  "hu" => "",
  "it" => "Numero massimo emails di digest:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_verp = array (
  "fr" => "VERP :",
  "en" => "VERP:",
  "hu" => "",
  "it" => "VERP:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_maxverprecips = array (
  "fr" => "Nombre max de destinataire VERP :",
  "en" => "Max VERP recipients:",
  "hu" => "",
  "it" => "Numero massimo di destinatari VERP:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_delimiter = array (
  "fr" => "Délimiteur :",
  "en" => "Delimiter:",
  "hu" => "",
  "it" => "Delimiter:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_owner = array (
  "fr" => "Propriétaire :",
  "en" => "Owner:",
  "hu" => "",
  "it" => "Proprietario:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_customheaders = array (
  "fr" => "Entetes personalisés :",
  "en" => "Custom headers:",
  "hu" => "",
  "it" => "Headers personalizzati:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_delheaders = array (
  "fr" => "Effacer les headers :",
  "en" => "Delete headers:",
  "hu" => "",
  "it" => "Cancella headers:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_access = array (
  "fr" => "Liste d'accès :",
  "en" => "Access list:",
  "hu" => "",
  "it" => "Lista d'accesso:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_title_footer = array (
  "fr" => "Pied de message aditionnel :",
  "en" => "Added footer:",
  "hu" => "",
  "it" => "Aggiungi footer:",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_list_name = array (
  "fr" => "Nom de la liste.",
  "en" => "Name of the list.",
  "hu" => "",
  "it" => "Nome della lista.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_main_owner = array (
  "fr" => "Ce champ contient l\'adresse de l\'administrateur principal de la liste.",
  "en" => "This is the main owner of the list.",
  "hu" => "",
  "it" => "Il propietario principale della lista.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_listaddress = array (
  "fr" => "Ce champ contient toutes les adresses que MLMMJ voit comme adresse de liste (voire l\'option tocc). La première est l\'adresse principale.",
  "en" => "This feild contains all addresses which mlmmj sees as listaddresses (see tocc option). The first one is the one used as the primary one, when mlmmj sends out mail.",
  "hu" => "",
  "it" => "Questo campo contiene gli indirizzi...",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_closedlist = array (
  "fr" => "La liste est-elle fermée. Si elle est fermée, les inscription et désinscription sont désactivées.",
  "en" => "Is the list is open or closed. If it\'s closed subscribtion and unsubscription via mail is disabled.",
  "hu" => "",
  "it" => "Se selezionato la lista è chiusa. Le iscrizioni e cancellazioni dalla lista sono disattivate.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_moderated = array (
  "fr" => "Si ce drapeau est positionné, alors la liste est modérée",
  "en" => "If this flag is set, the email addresses in the field moderators will act as moderators for the list.",
  "hu" => "",
  "it" => "Se selezionato, la lista diventa moderata.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_moderators = array (
  "fr" => "Ceci est la liste des modérateurs.",
  "en" => "This is the list of moderators.",
  "hu" => "",
  "it" => "Lista dei moderatori (1 per linea).",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_tocc = array (
  "fr" => "Si ce drapeau est positionné, la liste ne doit pas forcément être présente dans les champs To: ou Cc: du header du message.",
  "en" => "If this flag is set, the list address does not have to be in the To: or Cc: header of the email to the list.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_subonlypost = array (
  "fr" => "Quand ce drapeau est positionné, seuls les inscrits peuvent envoyer. La vérification est faite en fonction du &quot;From:&quot; du header.",
  "en" => "When this flag is set, only people who are subscribed to the list, are allowed to post to it. The check is made against the &quot;From:&quot; header.",
  "hu" => "",
  "it" => "Quando selezionato, solo gli iscritti potranno postare nella lista. La verifica viene effettuata nel campo &quot;From:&quot; dell\'header.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_prefix = array (
  "fr" => "Préfixe de la ligne Sujet: (Subject:) des messages de la liste. Ceci va altéré la ligne Sujet: et ajouter un préfixe si il n\'est pas déjà présent.",
  "en" => "The prefix for the Subject: line of mails to the list. This will alter the Subject: line, and add a prefix if it\'s not present elsewhere.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_owner = array (
  "fr" => "Les adresses emails de ces champs (1 par ligne) recevront les messages pour liste-owner@nom-de-domaine.tld",
  "en" => "The email addresses in this fields (1 per line) will get mails to listname-owner@listdomain.tld",
  "hu" => "",
  "it" => "Questi indirizzi email (1 per linea) riceveranno i messaggi destinati a lista-owner@dominio.tld.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_customheaders = array (
  "fr" => "Ces champs contiennent les champs qui doivent être ajouté a chaques message. C\'est ici que vous pouvez ajouter le champs Reply-To: dans le header si cela est ce que vous voulez.",
  "en" => "These headers are added to every mail coming through. This is the place you want to add Reply-To: header in case you want such.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_delheaders = array (
  "fr" => "Dans ces champs est spécifié *UN* token du header par ligne. Si les champs sont comme il suit :<br><br>Received:<br>Message-ID:<br><br>Alors toutes les occurences de ces headers dans les messages entrants de la liste seront effacé. From: et Return-Path: sont effacé dans tous les cas.",
  "en" => "In those fields is specified *ONE* headertoken to match per line. If the fields are like this:<br><br>Received:<br>Message-ID:<br><br>Then all occurences of these headers in incoming list mail will be deleted. From: and Return-Path: are deleted no matter what.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_access = array (
  "fr" => "Lire la partie README.access de la doc de MLMMJ.",
  "en" => "If this file exists, all headers of a post to the list is matched against the rules. The first rule to match wins. NOTE: the default action is to deny access (reject the mail) so take care if you write something here",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_footer = array (
  "fr" => "Remplissez ceci si vous voulez que tous les mails incluse quelquechose comme:<br>--<br>Pour vous désinscrire envoyez un message à coollist+unsubscribe@lists.domain.net.",
  "en" => "Fill this if you want every mail to have something like:<br>--<br>To unsubscribe send a mail to coollist+unsubscribe@lists.domain.net.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_memorymailsize = array (
  "fr" => "Ici est spécifié le nombre d\'octet que peut faire un message en mémoire pour être préparé à être envoyé. Default à 16Ko.",
  "en" => "Here is specified in bytes how big a mail can be and still be prepared for sending in memory. It\'s greatly reducing the amount of write system calls to prepare it in memory before sending it, but can also lead to denial of service attacks. Default is 16k (16384 bytes).",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_addtohdr = array (
  "fr" => "Lorsque ce drapeau est positionné un header To: incluant les adresses des destinataires sera ajouté aux messages sortants. La recommandation est de retiré les header To: grâce a l\'option delheaders au préalable (voir plus loin).",
  "en" => "When this flag is present, a To: header including the recipients emailaddress will be added to outgoing mail. Recommended usage is to remove existing To: headers with delheaders (see above) first.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_notifysub = array (
  "fr" => "Si ce drapeau est drapeau est positionné, alors le(s) propriétaire(s) recevront les adresses des (dé)enregistrement à la liste.",
  "en" => "If this flag is present, the owner(s) will get a mail with the address of someone sub/unsubscribing to a mailinglist.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_digestinterval = array (
  "fr" => "Cette valeur spécifie combien de secondes doivent passé avant que le nouveau digest soit déclanché. Le defaut est de 604800 secondes, ce qui correspond à 7 jours.",
  "en" => "This value specifies how many seconds will pass before the next digest is sent. Defaults to 604800 seconds, which is 7 days.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_digestmaxmails = array (
  "fr" => "Cette valeur définie combien de mails peuvent s\'accumulés avant qu\'un digest soit envoyé. Defaut de 50 message.",
  "en" => "This file specifies how many mails can accumulate before digest sending is triggered. Defaults to 50 mails, meaning that if 50 mails arrive to the list before digestinterval have passed, the digest is delivered.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_bouncelife = array (
  "fr" => "Ici est spécifié le nombre de secondes qu\'une adresse peut bouncer avant d\'être désinscrit. Le defaut est de 432000 secondes, ce qui est 5 jours.",
  "en" => "Here is specified for how long time in seconds an address can bounce before it\'s unsubscribed. Defaults to 432000 seconds, which is 5 days.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_noarchive = array (
  "fr" => "Si ce drapeau est positionné, alors le mail n\'est pas sauvé dans l\'archive mais simplement effacé.",
  "en" => " If this flag exists, the mail won\'t be saved in the archive but simply deleted.",
  "hu" => "",
  "it" => "Se selezionato le email non verranno salvate nell\'archivio ma semplicemente cancellate.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_nosubconfirm = array (
  "fr" => "Si ce drapeau existe, aucun mail de confirmation est nécéssaire pour s\'inscrire à la liste. Ceci ne doit en pratique être utilisé que dans un réseau local. A UTILISER AVEC PRECAUTION!",
  "en" => "If this flag exists, no mail confirmation is needed to subscribe to the list. This should in principle never ever be used, but there is times on local lists etc. where this is useful. HANDLE WITH CARE!",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_noget = array (
  "fr" => "Si ce drapeau est positionné, récupérer des posts avec -get-N (par exemple maliste-get-12@mon-domaine.tld) est désactivé.",
  "en" => "If this file exists, then retrieving old posts with -get-N (for exemple mylist-get-12@my-domain.tld) is disabled",
  "hu" => "",
  "it" => "Se selezionato la possibilità di recuperare vecchi posts con -get-N è disabilitata.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_subonlyget = array (
  "fr" => "Si ce drapeau existe, récupéré des posts avec -get-N est possible uniquement pour les inscrits a la liste. Le drapeau \'noget\' est prioritaire.",
  "en" => "If this file exists, then retrieving old posts with -get-N is only possible for subscribers. The above mentioned \'noget\' have precedence.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_verp = array (
  "fr" => "Active le support VERP.",
  "en" => "Enable VERP support.",
  "hu" => "",
  "it" => "Attiva il supporto VERP.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_maxverprecips = array (
  "fr" => "Combien de destinataire par mail doivent être envoyé au serveur SMTP. Le defaut est de 100.",
  "en" => "How many recipients pr. mail delivered to the smtp server. Defaults to 100.",
  "hu" => "",
  "it" => "",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_notoccdenymails = array (
  "fr" => "Refuse les message si ni le To: ni le Cc: contient l\'une des adresses de la liste.",
  "en" => "Reject mails that don\'t have the list adress in the To: or Cc:.",
  "hu" => "",
  "it" => "Rifiuta tutte le email che non contengono l\indirizzo della lista su To: o Cc:.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_noaccessdenymails = array (
  "fr" => "-",
  "en" => "-",
  "hu" => "",
  "it" => "-",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_nosubonlydenymails = array (
  "fr" => "-",
  "en" => "-",
  "hu" => "",
  "it" => "-",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_delimiter = array (
  "fr" => "Ne pas modifier a moins que vous sachiez vraiment ce que vous faites.",
  "en" => "Do not change unless you really know what you are doing.",
  "hu" => "",
  "it" => "Non cambiare a meno che tu non sappia quello che stai facendo.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

$txt_lists_hlp_relayhost = array (
  "fr" => "Serveur de mail utilisé pour les envois.",
  "en" => "Mail server used to send the messages.",
  "hu" => "",
  "it" => "Server mail usato per inviare messaggi.",
  "nl" => "",
  "ru" => "",
  "de" => "",
  "zh" => "",
  "pl" => "",
  "es" => "",
  "pt" => "");

?>